service: polyconf-async

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  promise:
    handler: handler.helloPromise
    events:
      - http:
          path: hello-promise
          method: get

  # async:
  #   handler: handler.helloAsync
  #   events:
  #     - http:
  #         path: hello-async
  #         method: get
